/' caracteres em OEM
ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
บ Arquivo:Subrotinas.inc ,cabealho das Rotinas           บ
ฬอออออออออออออออออออออออออออออออออออออออออออออออออออออออออน
บ - sub ===> pausa - interompe e mopstra uma mensagem     บ
ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ'/
Public sub Pausa()
    Print
    Print "Pressione qualquer tecla para continuar. . ..";
    Sleep
end sub
/'
ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
บ - SUB ===> Fim()  - rotina de final de programa         บ
ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ'/
public sub fim()
    dim x as integer = principal
    Pausa
    end x
end sub


