/' caracteres em OEM
ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
บ Arquivo:Subrotinas.inc ,cabealho das Rotinas           บ
ฬอออออออออออออออออออออออออออออออออออออออออออออออออออออออออน
บ - sub ===> pausa - interompe e mopstra uma mensagem     บ
ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ'/
Public sub Pausa
    Print
    Print "Pressione qualquer tecla para continuar. . ..";
    Sleep
   ' cls
end sub
/'
ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
บ - SUB ===> Fim()  - rotina de final de programa         บ
ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ'/
public sub Fim()
    dim sair as integer
    sair = principal
    Pausa
    end sair
end sub


