/' caracteres em OEM
ษออออออออออออออออออออออออออออออออออออออออออออออออออออออป
บ Arquivo:Subrotinas.inc ,cabealho das Rotinas        บ
ศออออออออออออออออออออออออออออออออออออออออออออออออออออออผ'/
/'
ษออออออออออออออออออออออออออออออออออออออออออออออออออออออป
บ - sub ===> pausa - interompe e mopstra uma mensagem  บ
ศออออออออออออออออออออออออออออออออออออออออออออออออออออออผ'/
Public sub Pausa
    Print
    Print "Pressione qualquer tecla para continuar. . ..";
    Sleep
    cls
end sub
/'
ษออออออออออออออออออออออออออออออออออออออออออออออออออออออป
บ - SUB ===> Fim()  - rotina de final de programa      บ
ศออออออออออออออออออออออออออออออออออออออออออออออออออออออผ'/
public sub Fim
    Pausa
end sub


